"""Common English typo wordlist for auto_typo (720+ correct→typo mappings)."""

from typing import Dict, List

# correct spelling -> plausible typo forms (transpositions, fat-finger, classic traps)
RAW_MISSPELLINGS: Dict[str, List[str]] = {
    "the": ["teh", "hte", "th"],
    "and": ["adn", "nad", "annd"],
    "for": ["fro", "fo", "fir"],
    "not": ["nto", "ont"],
    "but": ["btu", "buts"],
    "you": ["yuo", "uou", "yiu"],
    "your": ["yuor", "yoru", "youre", "you're"],
    "you're": ["your", "youre", "you'er"],
    "yours": ["yousr", "yuors"],
    "they": ["tehy", "thye", "thay"],
    "them": ["tehm", "thme"],
    "their": ["thier", "tehir", "thire", "there", "they're"],
    "they're": ["their", "theyre", "they'r"],
    "there": ["thier", "ther", "tehre", "their", "they're"],
    "these": ["tehse", "thsee"],
    "those": ["thsoe", "tsohe"],
    "this": ["tihs", "htis", "thsi"],
    "that": ["taht", "tahat", "htat"],
    "than": ["thna", "tahn"],
    "then": ["thne", "tehn"],
    "with": ["wiht", "wtih", "wih"],
    "from": ["form", "fomr", "frmo"],
    "have": ["ahve", "hvae", "haev"],
    "has": ["ahs", "hsa"],
    "had": ["ahd", "hda"],
    "was": ["wsa", "aws"],
    "were": ["weer", "wre"],
    "we're": ["were", "we'er", "weer"],
    "we've": ["weve", "we'ev"],
    "we'll": ["well", "we'l", "weill"],
    "been": ["bene", "eben"],
    "being": ["beign", "biegn"],
    "will": ["wil", "wll", "wiil"],
    "would": ["woudl", "wuld", "woud"],
    "could": ["coudl", "culd", "cuold"],
    "should": ["shoudl", "shuld", "shoud"],
    "can": ["cna", "acn"],
    "just": ["jsut", "juts", "juust"],
    "only": ["onyl", "olny"],
    "also": ["aslo", "olsa"],
    "very": ["vrey", "veery"],
    "even": ["eevn", "evne"],
    "some": ["soem", "smoe"],
    "any": ["ayn", "nay"],
    "all": ["al", "ll"],
    "one": ["oen", "noe"],
    "two": ["tow", "towo"],
    "too": ["to", "tooo"],
    "into": ["inot", "itno"],
    "over": ["oevr", "ovre"],
    "after": ["afetr", "aftre"],
    "before": ["befroe", "befor", "bfore"],
    "about": ["abotu", "abut", "baout"],
    "around": ["aroudn", "arund"],
    "between": ["betwene", "bewteen"],
    "through": ["thru", "throuhg", "trhough"],
    "though": ["tho", "thoug", "tough"],
    "although": ["altho", "altough", "allthough"],
    "without": ["wihtout", "withotu"],
    "within": ["wihtin", "withni"],
    "because": ["becuase", "becase", "becuse"],
    "until": ["untill", "untl", "unitl"],
    "while": ["hwile", "whlie"],
    "when": ["wehn", "whne", "whem"],
    "where": ["wheer", "wehre", "whre"],
    "what": ["waht", "whta", "whaat"],
    "which": ["whcih", "wich", "whihc"],
    "who": ["whi", "woh"],
    "why": ["whyy"],
    "how": ["hwo"],
    "here": ["heere", "hre"],
    "her": ["hre", "ehr"],
    "him": ["hmi", "ihm"],
    "his": ["hsi", "ihs"],
    "she": ["hse"],
    "our": ["oru", "uor"],
    "out": ["uot", "otu"],
    "off": ["of", "offf"],
    "own": ["onw"],
    "way": ["awy", "wya"],
    "say": ["asy", "sya"],
    "said": ["siad", "saidd"],
    "says": ["syas"],
    "get": ["gte", "egt"],
    "got": ["ogt"],
    "let": ["lte"],
    "put": ["upt", "ptu"],
    "use": ["ues", "sue"],
    "used": ["uesd", "usd"],
    "using": ["useing", "usign"],
    "make": ["amke", "mkae"],
    "made": ["mdae", "amde"],
    "take": ["tkae", "atke"],
    "took": ["tookk", "otok"],
    "give": ["gvie", "igve"],
    "given": ["givin", "givne"],
    "come": ["ocme", "cmoe"],
    "came": ["caem", "acme"],
    "goes": ["oges", "gose"],
    "going": ["goign", "oging", "goiing"],
    "gone": ["ogne", "gnoe"],
    "want": ["wnat", "awnt"],
    "wanted": ["wantted", "wnated"],
    "need": ["ned"],
    "needed": ["needded", "neded"],
    "try": ["rty", "tyr"],
    "tried": ["tired", "tryed"],
    "trying": ["tryign", "tyring"],
    "look": ["loko", "olok"],
    "looked": ["lookked", "lokoked"],
    "looking": ["lookign", "lokking"],
    "see": ["ese"],
    "seen": ["seenn", "esne"],
    "know": ["knoe", "konw", "knwo"],
    "known": ["knwon"],
    "think": ["thikn", "tihnk", "htink"],
    "thought": ["thoguht", "tought", "thougt"],
    "thinking": ["thinkign", "thniking"],
    "feel": ["fele", "efel"],
    "felt": ["flet", "eflt"],
    "mean": ["maen", "amen"],
    "means": ["maens"],
    "seem": ["seme", "esem"],
    "seems": ["seemms", "smees"],
    "keep": ["kepe", "ekpe"],
    "kept": ["kpet", "ekpt"],
    "help": ["hlep", "ehlp"],
    "helps": ["hleps", "helsp"],
    "find": ["fidn"],
    "found": ["foudn", "fuond"],
    "tell": ["tlel"],
    "told": ["toldd", "otld"],
    "ask": ["aks", "sak"],
    "asked": ["askked", "aksed"],
    "work": ["wokr", "owrk"],
    "works": ["wokrs", "wrkos"],
    "working": ["workign", "wroking"],
    "worked": ["workked", "wroked"],
    "call": ["clal", "acll"],
    "called": ["callled", "cllled"],
    "start": ["strat", "satrt"],
    "started": ["startted", "strated"],
    "stop": ["sotp", "tosp"],
    "run": ["urn", "rnu"],
    "running": ["runing", "runnign"],
    "move": ["moev", "omve"],
    "live": ["lvie", "ilve"],
    "leave": ["laeve", "levea"],
    "left": ["lfet"],
    "turn": ["trun", "utrn"],
    "hand": ["hnd", "ahnd"],
    "head": ["haed"],
    "face": ["fcae", "afce"],
    "place": ["palce", "plcae"],
    "point": ["piont", "poitn"],
    "part": ["prat", "aprt"],
    "side": ["sied", "isde"],
    "line": ["ilne", "lnie"],
    "word": ["wrod", "owrd"],
    "name": ["nmae", "anme"],
    "thing": ["thign", "hting"],
    "things": ["thigns", "htings"],
    "stuff": ["stuf", "sutff"],
    "time": ["tiem", "itme"],
    "times": ["tiems", "itmes"],
    "day": ["dya", "ady"],
    "days": ["dasy", "adys"],
    "week": ["wek"],
    "month": ["mnoth", "motnh"],
    "year": ["yaer", "yera"],
    "today": ["toady"],
    "tomorrow": ["tommorrow", "tommorow", "tomorow"],
    "yesterday": ["yesturday", "yesterady", "yestarday"],
    "morning": ["moring", "mornign"],
    "night": ["ngiht"],
    "weekend": ["wekend", "weeken"],
    "people": ["peopel", "poeple"],
    "person": ["pesron", "persno"],
    "someone": ["somone", "someoen", "soemone"],
    "anyone": ["anyoen"],
    "everyone": ["everone", "everyoen"],
    "everybody": ["everbody", "everybdy"],
    "somebody": ["sombdy", "somebdy"],
    "friend": ["freind", "frend", "frined"],
    "friends": ["freinds", "frineds"],
    "family": ["famliy", "familly"],
    "world": ["wrold", "owrld"],
    "life": ["lfie", "ilfe"],
    "game": ["gaem", "agme"],
    "play": ["paly", "aply"],
    "player": ["playre"],
    "team": ["taem", "atem"],
    "group": ["gorup", "gruop"],
    "server": ["sever", "servre", "servr"],
    "channel": ["chanell", "chanel", "chnanel"],
    "message": ["mesage", "messge", "messege"],
    "messages": ["mesages", "messges"],
    "reply": ["relpy", "rply"],
    "chat": ["caht", "chta"],
    "code": ["ocde", "cdoe"],
    "file": ["fiel", "ifle"],
    "test": ["tets", "etst"],
    "testing": ["testign", "tetsing"],
    "fix": ["fxi", "ifx"],
    "fixed": ["fixxed", "fxied"],
    "broken": ["borken", "brokn"],
    "wrong": ["worng", "wrnog"],
    "right": ["rigth", "rihgt", "rgiht"],
    "true": ["treu"],
    "false": ["flase", "fasle"],
    "maybe": ["mabye", "mayb", "mabe"],
    "probably": ["prolly", "probbably", "porbably"],
    "definitely": ["definately", "definatly", "defintely", "defiantly", "definitly"],
    "absolutely": ["absolutly", "absoluetly", "absolutley"],
    "literally": ["litreally", "litterally", "literalyl"],
    "basically": ["basicly", "basicaly", "basicalyl"],
    "actually": ["actualy", "acutally", "actaully"],
    "really": ["realy", "realyl", "rly"],
    "pretty": ["prety", "prettey", "prettty"],
    "totally": ["totaly", "totallly"],
    "usually": ["usally", "usualy"],
    "especially": ["especialy", "expecially", "espescially"],
    "specifically": ["specificly", "specificaly"],
    "generally": ["generaly"],
    "finally": ["finaly", "finallly"],
    "eventually": ["eventualy", "eventuallly"],
    "obviously": ["obviousy", "obviosuly"],
    "seriously": ["seriousy", "seriosuly"],
    "honestly": ["honstly"],
    "apparently": ["apparantly", "aparently"],
    "currently": ["curently", "currnetly"],
    "recently": ["recnetly"],
    "already": ["allready", "alreayd", "aready"],
    "always": ["allways"],
    "never": ["nevr"],
    "sometimes": ["somtimes", "soemtimes"],
    "anything": ["anythign", "anyhting"],
    "something": ["somthing", "somethign", "soemthing"],
    "everything": ["everthing", "everythign"],
    "nothing": ["nothign"],
    "awesome": ["awsome", "awsum", "awesmoe"],
    "thanks": ["thnks", "thx", "thankss"],
    "thank": ["thnak", "thakn"],
    "please": ["plase", "pleae"],
    "sorry": ["sory", "soory"],
    "hello": ["helo", "hllo"],
    "okay": ["okya", "oaky"],
    "cool": ["col"],
    "nice": ["ncie", "niec"],
    "great": ["graet", "greta"],
    "good": ["godo", "ogod"],
    "best": ["bset"],
    "better": ["bettr", "beter"],
    "bad": ["abd", "dba"],
    "worse": ["wrose"],
    "weird": ["wierd", "werid", "wird"],
    "funny": ["funy"],
    "happy": ["hapy"],
    "sad": ["asd", "sda"],
    "love": ["lvoe", "olve"],
    "hate": ["htae", "ahte"],
    "like": ["liek", "ilke"],
    "liked": ["liekd"],
    "hope": ["hoep"],
    "wish": ["wihs", "iwsh"],
    "wait": ["wiat", "awit"],
    "ready": ["readdy", "raedy"],
    "sure": ["suer"],
    "fine": ["fien", "ifne"],
    "easy": ["eays", "aesy"],
    "hard": ["hrd", "ahrd"],
    "quick": ["quik"],
    "fast": ["fats", "afst"],
    "slow": ["solw"],
    "long": ["lnog", "olng"],
    "short": ["shrot"],
    "little": ["litle", "litte", "littel"],
    "small": ["smal", "samll"],
    "big": ["ibg", "bgi"],
    "new": ["enw"],
    "old": ["odl"],
    "same": ["smae", "asme"],
    "different": ["diferent", "diffrent", "differnt"],
    "another": ["anther", "anotehr"],
    "other": ["ohter", "otehr"],
    "others": ["ohters", "otehrs"],
    "first": ["frist", "fisrt"],
    "second": ["secodn", "sceond"],
    "third": ["thrid", "tihrd"],
    "last": ["lsat", "alst"],
    "next": ["enxt"],
    "once": ["ocne"],
    "again": ["agin", "agian"],
    "still": ["sitll"],
    "yet": ["yte"],
    "back": ["bakc", "abck"],
    "away": ["awya"],
    "together": ["togehter", "togther"],
    "however": ["howver", "howevre"],
    "instead": ["instaed"],
    "enough": ["enoguh", "enouhg", "enuf"],
    "lot": ["lto", "olt"],
    "lots": ["lotss"],
    "bit": ["bti", "ibt"],
    "kind": ["knid"],
    "sort": ["srot", "osrt"],
    "type": ["tyep", "ytpe"],
    "idea": ["idae"],
    "reason": ["reson", "reaosn"],
    "problem": ["probelm", "porblem"],
    "issue": ["isue"],
    "question": ["quesiton", "qestion"],
    "answer": ["asnwer", "anwser"],
    "example": ["exmaple", "exampel"],
    "change": ["chnage", "cahnge"],
    "changed": ["chagned", "chnaged"],
    "update": ["udpate", "updaet"],
    "updated": ["updaetd", "udpated"],
    "version": ["verison", "verson"],
    "feature": ["feautre", "featuer"],
    "option": ["opiton", "optino"],
    "settings": ["setttings", "setings"],
    "default": ["defualt", "defautl"],
    "error": ["erorr", "errro"],
    "errors": ["erorrs", "errros"],
    "bug": ["bgu", "ubg"],
    "bugs": ["bgus", "ubgs"],
    "patch": ["ptach"],
    "install": ["instal", "insatll"],
    "installed": ["instaled", "insatlled"],
    "download": ["donwload", "downlaod"],
    "upload": ["uplaod", "upoad"],
    "delete": ["delet", "deltete"],
    "remove": ["remvoe", "reomve"],
    "add": ["dda"],
    "added": ["addded", "aded"],
    "create": ["cretae"],
    "created": ["cretaed", "crated"],
    "build": ["buidl", "bulid"],
    "write": ["wrtie"],
    "written": ["writen"],
    "read": ["raed"],
    "reading": ["readign", "raeding"],
    "send": ["sned", "esnd"],
    "sent": ["snet", "esnt"],
    "show": ["shwo", "sohw"],
    "shown": ["shwon"],
    "hide": ["hied", "ihde"],
    "open": ["opne"],
    "close": ["colse"],
    "closed": ["clsed", "colsed"],
    "save": ["sae", "asve"],
    "saved": ["svaed"],
    "load": ["laod", "loda"],
    "loading": ["loadign", "laoding"],
    "waiting": ["waitign"],
    "check": ["chekc", "chcek"],
    "checked": ["chekced", "chceked"],
    "verify": ["verfy", "veirfy"],
    "confirm": ["confrim", "confirmm"],
    "ignore": ["ignroe"],
    "remember": ["rember", "remeber"],
    "forget": ["forgt", "foget"],
    "learn": ["lern", "laern"],
    "learning": ["learnign"],
    "understand": ["understadn", "undestand"],
    "explain": ["explan", "expalin"],
    "meaning": ["meanign", "menaing"],
    "important": ["importent", "importnat", "improtant"],
    "interesting": ["intresting", "intersting"],
    "possible": ["posible", "possibile"],
    "impossible": ["impossibel", "imposible"],
    "available": ["availible", "availabe"],
    "simple": ["simpe", "simlpe"],
    "complex": ["complx", "compex"],
    "complete": ["compleat", "compete"],
    "completed": ["compleated", "compelted"],
    "finish": ["finsih", "finsh"],
    "finished": ["finisehd", "finshed"],
    "begin": ["beign", "begni"],
    "beginning": ["begining", "beginnig"],
    "continue": ["continu"],
    "pause": ["psue"],
    "resume": ["resum"],
    "retry": ["retyr"],
    "success": ["sucess", "succes"],
    "successful": ["sucessful", "succesful"],
    "fail": ["flai"],
    "failed": ["faild"],
    "failure": ["failuer", "faliure"],
    "random": ["randmo"],
    "normal": ["noraml", "norml"],
    "receive": ["recieve", "recive"],
    "received": ["recieved", "recived"],
    "believe": ["beleive", "belive", "beleve"],
    "achievement": ["achievment", "acheivement"],
    "achieve": ["acheive", "achive"],
    "ceiling": ["cieling", "ceilng"],
    "piece": ["peice", "pice", "peace"],
    "field": ["feild", "fiedl"],
    "brief": ["breif", "beirf"],
    "chief": ["cheif", "chife"],
    "seize": ["sieze", "seeze"],
    "leisure": ["liesure", "leasure"],
    "foreign": ["foriegn", "forign"],
    "height": ["hieght", "heigth"],
    "weight": ["wieght", "weigth"],
    "neighbor": ["neighbour", "nieghbor"],
    "separate": ["seperate", "seperete", "saparate", "seprate"],
    "separated": ["seperated", "saparated"],
    "occurrence": ["occurance", "occurence", "ocurrance"],
    "occurred": ["occured", "ocurred"],
    "occasionally": ["ocassionally", "occasionaly", "ocasionally", "ocasionaly"],
    "occasion": ["ocassion", "occaison"],
    "accommodate": ["accomodate", "accommadate"],
    "accommodation": ["accomodation", "accommadation"],
    "embarrass": ["embarass", "embarras"],
    "embarrassed": ["embarassed", "embarrased"],
    "embarrassing": ["embarassing", "embarrasing"],
    "millennium": ["millenium", "milennium"],
    "millennia": ["millenia", "milennia"],
    "maintenance": ["maintainance", "maintenence"],
    "privilege": ["priviledge", "privelege"],
    "privileged": ["priviledged", "priveleged"],
    "judgment": ["judgement"],
    "argument": ["arguement", "arguemnt"],
    "environment": ["enviroment", "enviornment"],
    "environmental": ["enviromental", "enviornmental"],
    "government": ["goverment", "governmnet"],
    "independent": ["independant", "indpendent"],
    "independence": ["independance", "indpendence"],
    "dependent": ["dependant", "dependnet"],
    "existence": ["existance", "exsistence"],
    "existent": ["existant", "exsistent"],
    "persistent": ["persistant", "persistnet"],
    "consistency": ["consistancy", "consistensy"],
    "consistent": ["consistant"],
    "resistance": ["resistence", "resitance"],
    "assistant": ["assistent", "asistant"],
    "assistance": ["assistence", "asistance"],
    "performance": ["performence", "preformance"],
    "performed": ["performd", "preformed"],
    "preferred": ["prefered", "preffered"],
    "prefer": ["preffer", "prefre"],
    "reference": ["referance", "refrence"],
    "referred": ["refered", "reffered"],
    "transfer": ["transer", "tranfer"],
    "transferred": ["transfered", "tranferred"],
    "surprise": ["suprise", "surprize"],
    "surprised": ["suprised", "surprized"],
    "desperate": ["desparate", "desprate"],
    "desperately": ["desparately", "desprately"],
    "necessary": ["neccessary", "necesary", "neccesary"],
    "unnecessary": ["unneccessary", "unnecesary"],
    "necessity": ["necesity", "neccessity"],
    "accessory": ["accesory", "accessery"],
    "access": ["acces", "acess"],
    "accessible": ["accessable", "accesible"],
    "address": ["adress", "addres"],
    "addressed": ["adressed", "addresed"],
    "successfully": ["succesfully", "sucessfully"],
    "business": ["buisness", "busines"],
    "busyness": ["business", "busynes"],
    "beginner": ["beginer", "begginer"],
    "recommend": ["reccomend", "recomend"],
    "recommended": ["reccomended", "recomended"],
    "recommendation": ["reccomendation", "recomendation"],
    "committed": ["comitted", "commited"],
    "commitment": ["committment", "commitement"],
    "committee": ["comittee", "commitee"],
    "immediately": ["immediatly", "imediately"],
    "immediate": ["immediat", "imediate"],
    "publicly": ["publically", "pubicly"],
    "basic": ["baisc"],
    "truly": ["truley", "turly"],
    "genuinely": ["geniunely", "genuienly"],
    "particularly": ["particulary", "particularily"],
    "accidentally": ["accidently", "accidentaly"],
    "incidentally": ["incidently", "incidentaly"],
    "gradually": ["gradualy"],
    "personally": ["personaly", "personnally"],
    "physically": ["physicaly", "physcially"],
    "psychology": ["pychology", "psycology"],
    "psychological": ["pychological", "psycological"],
    "rhythm": ["rythm", "rhytm"],
    "rhythmic": ["rythmic", "rhytmic"],
    "library": ["libary", "librery"],
    "librarian": ["libarian", "librerian"],
    "February": ["Febuary", "Feburary"],
    "Wednesday": ["Wensday", "Wednsday"],
    "calendar": ["calender", "calander"],
    "schedule": ["scedule", "schedual"],
    "scheduled": ["sceduled", "schedualed"],
    "parallel": ["paralel", "parralel"],
    "parallelism": ["paralelism", "parralelism"],
    "category": ["catagory", "categroy"],
    "categories": ["catagories", "categroies"],
    "hierarchy": ["heirarchy", "hierachy"],
    "bureaucracy": ["beaurocracy", "bureacracy"],
    "bureau": ["beauro", "bureu"],
    "liaison": ["liason", "liasion"],
    "conscience": ["concience", "consciense"],
    "conscious": ["consious", "concious"],
    "consciousness": ["consiousness", "conciousness"],
    "subconscious": ["subconsious", "subconcious"],
    "discipline": ["disipline", "disciplin"],
    "disciplined": ["disiplined", "disciplned"],
    "license": ["lisence", "licence"],
    "practice": ["practise", "practce"],
    "practiced": ["practised", "practced"],
    "practical": ["practicle", "practial"],
    "practically": ["practicly", "practialy"],
    "lightning": ["lightening", "lighnting"],
    "lightening": ["lightning", "lightenning"],
    "fascinating": ["facinating", "fascinatiing"],
    "fascinate": ["facinate", "fasinate"],
    "mischievous": ["mischievious", "mischevious"],
    "mischief": ["mischif", "mischeif"],
    "questionnaire": ["questionaire", "questionnare"],
    "conscientious": ["consciencious", "consientious"],
    "conscientiousness": ["conscienciousness", "consientiousness"],
    "miscellaneous": ["miscellanous", "miscellaneus"],
    "pronunciation": ["pronounciation", "pronouncation"],
    "pronounce": ["pronunce", "pronouce"],
    "pronounced": ["pronunced", "pronouced"],
    "exaggerate": ["exagerate", "exaggarate"],
    "exaggerated": ["exagerated", "exaggarated"],
    "aggravate": ["agravate", "aggravaate"],
    "aggregate": ["agregate", "aggreagate"],
    "aggressive": ["agressive", "aggresive"],
    "aggression": ["agression", "aggresion"],
    "supersede": ["supercede", "superceed"],
    "superseded": ["superceded", "superceeded"],
    "precede": ["preceed", "precedee"],
    "preceded": ["preceeded", "precedeed"],
    "proceed": ["procede", "proceeed"],
    "proceeded": ["proceded", "proceeeded"],
    "proceeding": ["proceding", "proceeeding"],
    "proceedings": ["procedings", "proceeedings"],
    "cemetery": ["cemetary"],
    "stationary": ["stationery", "statinary"],
    "stationery": ["stationary", "statinary"],
    "principal": ["principle", "prinicipal"],
    "principle": ["principal", "prinicple"],
    "compliment": ["complement", "complimnt"],
    "complement": ["compliment", "complment"],
    "desert": ["dessert", "dessrt"],
    "dessert": ["desert", "desrt"],
    "lose": ["loose"],
    "loose": ["lose"],
    "loosing": ["losing", "loosign"],
    "losing": ["loosing", "losign"],
    "affect": ["effect", "afect"],
    "effect": ["affect", "efect"],
    "accept": ["except", "acept"],
    "except": ["accept", "exept"],
    "advice": ["advise"],
    "advise": ["advice"],
    "breath": ["breathe", "breth"],
    "breathe": ["breath", "brethe"],
    "breathing": ["brething", "breathign"],
    "choose": ["chose"],
    "chose": ["choose", "chsoe"],
    "chosen": ["choosen", "chsoen"],
    "lead": ["led", "laed"],
    "led": ["lead", "ld"],
    "past": ["passed"],
    "passed": ["past"],
    "quiet": ["quite"],
    "quite": ["quiet", "qutie"],
    "peace": ["piece"],
    "whole": ["hole"],
    "hole": ["whole"],
    "weather": ["whether", "wether"],
    "whether": ["weather", "wheather"],
    "its": ["it's"],
    "it's": ["its"],
    "whose": ["who's", "whos"],
    "who's": ["whose", "whos"],
    "alot": ["allot"],
    "allot": ["alot"],
    "cannot": ["cant"],
    "alright": ["alrigt"],
    "everyday": ["everday"],
    "anyway": ["anywy"],
    "anymore": ["anymor"],
    "noone": ["no-one"],
    "affection": ["affecton"],
    "fulfill": ["fullfill", "fullfil"],
    "fulfilled": ["fullfilled", "fullfiled"],
    "fulfillment": ["fullfillment", "fullfilment"],
    "fulfil": ["fullfil", "fulfile"],
    "skillful": ["skilful", "skillfull"],
    "willful": ["wilful", "willfull"],
    "grateful": ["greatful", "gratefull"],
    "gratefully": ["greatfully"],
    "temperate": ["temperatre", "temprate"],
    "desolate": ["desloate"],
    "appreciate": ["apreciate"],
    "appreciated": ["apreciated"],
    "appropriate": ["appropiate", "approprate"],
    "inappropriate": ["inappropiate", "inapproprate"],
    "approximate": ["aproximate", "approxiamte"],
    "approximately": ["aproximately", "approxiamtely"],
    "associate": ["assosiate", "asociate"],
    "associated": ["assosiated", "asociated"],
    "association": ["assosiation", "asociation"],
    "assassinate": ["assasinate"],
    "assassination": ["assasination", "assasinaton"],
    "harass": ["harrass", "haras"],
    "harassed": ["harrassed", "harased"],
    "harassment": ["harrassment", "harasment"],
    "interrupt": ["interupt"],
    "interrupted": ["interupted"],
    "interruption": ["interuption"],
    "interpret": ["interprete", "intepret"],
    "interpretation": ["intepretation"],
    "misinterpret": ["misinterprete", "misintepret"],
    "restaurant": ["restaraunt", "restraunt"],
    "restaurants": ["restaraunts", "restraunts"],
    "guarantee": ["garantee", "guarentee"],
    "guaranteed": ["garanteed", "guarenteed"],
    "guarantees": ["garantees", "guarentees"],
    "warranty": ["warrenty"],
    "guaranty": ["garanty", "guarenty"],
    "lieutenant": ["leutentant", "lieutentant"],
    "sergeant": ["sargent", "sergant"],
    "colonel": ["kernel", "coronel"],
    "bizarre": ["bizzare"],
    "bazaar": ["bazar", "baazar"],
    "minuscule": ["miniscule"],
    "maneuver": ["manoeuvre", "manuver"],
    "manoeuvre": ["maneuver", "manuver"],
    "acknowledgment": ["acknowledgement", "acknowlegment"],
    "acknowledge": ["acknowlege", "acknowlede"],
    "acknowledged": ["acknowleged", "acknowledeged"],
    "connoisseur": ["connoiseur", "conoisseur"],
    "fluorescent": ["flourescent", "florescent"],
    "fluorescence": ["flourescence", "florescence"],
    "pharaoh": ["pharoah"],
    "diarrhea": ["diarhea", "diarreah"],
    "diarrhoea": ["diarhoea", "diarreah"],
    "pneumonia": ["nuemonia", "pneumonea"],
    "pseudonym": ["seudonym", "pseudonim"],
    "psychiatrist": ["pychiatrist", "psyciatrist"],
    "psychiatry": ["pychiatry", "psyciatry"],
    "psychic": ["pychic", "psycic"],
    "psychotic": ["pychotic", "psycotic"],
    "psychopath": ["pychopath", "psycopath"],
    "psychopathology": ["pychopathology", "psycopathology"],
    "archaeology": ["archeology", "archaeolgy"],
    "archaeologist": ["archeologist", "archaeolgist"],
    "palaeontology": ["paleontology", "palaeontolgy"],
    "pediatric": ["paediatric"],
    "pediatrician": ["paediatrician"],
    "anesthetic": ["anaesthetic"],
    "anesthesia": ["anaesthesia"],
    "hemoglobin": ["haemoglobin", "hemoglobn"],
    "hemorrhage": ["haemorrhage", "hemorhage"],
    "hemorrhoid": ["haemorrhoid", "hemorhoid"],
    "maneuverability": ["manoeuvrability", "manuverability"],
    "manufacture": ["manufacure", "manufactre"],
    "manufactured": ["manufacured", "manufactred"],
    "manufacturer": ["manufacurer", "manufactrer"],
    "manufacturing": ["manufacuring", "manufactring"],
    "entrepreneur": ["entrepeneur", "entreprenuer"],
    "entrepreneurial": ["entrepeneurial", "entreprenurial"],
    "bureaucratic": ["beaurocratic", "bureacratic"],
    "bureaucrat": ["beaurocrat", "bureacrat"],
    "bureaucrats": ["beaurocrats", "bureacrats"],
    "questionnaires": ["questionaires", "questionnares"],
    "connoisseurs": ["connoiseurs", "conoisseurs"],
    "liaisons": ["liasons", "liasions"],
    "supersedes": ["supercedes", "superceeds"],
    "superseding": ["superceding", "superceeding"],
    "don't": ["dont", "do'nt", "dnt"],
    "doesn't": ["doesnt", "dosen't", "dosnt"],
    "didn't": ["didnt", "did'nt"],
    "isn't": ["isnt", "is'nt"],
    "aren't": ["arent", "are'nt"],
    "wasn't": ["wasnt", "was'nt"],
    "weren't": ["werent", "were'nt"],
    "haven't": ["havent", "have'nt"],
    "hasn't": ["hasnt", "has'nt"],
    "hadn't": ["hadnt", "had'nt"],
    "won't": ["wont", "wo'nt"],
    "wouldn't": ["wouldnt", "would'nt"],
    "couldn't": ["couldnt", "could'nt"],
    "shouldn't": ["shouldnt", "should'nt"],
    "can't": ["cant", "ca'nt", "cna't"],
    "I'm": ["im", "Im"],
    "I'll": ["ill", "Ill", "I'l"],
    "I've": ["ive"],
    "I'd": ["id"],
    "you'll": ["youll", "you'l"],
    "you've": ["youve", "you'ev"],
    "you'd": ["youd"],
    "they'll": ["theyll", "they'l"],
    "they've": ["theyve", "they'ev"],
    "they'd": ["theyd"],
    "we'd": ["wed"],
    "she's": ["shes"],
    "he's": ["hes"],
    "that's": ["thats", "taht's"],
    "what's": ["whats"],
    "there's": ["theres"],
    "here's": ["heres"],
    "let's": ["lets"],
    "gonna": ["gona"],
    "wanna": ["wana"],
    "gotta": ["gota"],
}
